Repository SilvaneUX/donut-test, pull requests merged in 2022-10, with the labels that each got.

#30 add olpro
  Programing Language/C family/C++/polynomial_integral.cpp
  Programing Language/C family/C/Queue.c
  Programing Language/C family/C/QuickSort.c
  Programing Language/C family/C/SelectionSort.c
  Programing Language/C family/C/SingleLinkedList.c
  Programing Language/C family/C/Stack.c
  Programing Language/C family/C/Tree.c
  Programing Language/C family/C/allSearchAlgorithm.c
  Programing Language/C family/C/bubblesort.c
  Programing Language/C family/C/buble sort.c
  Programing Language/C family/C/doubleLinkedList.c
  Programing Language/C family/C/file_operation.c
  Programing Language/C family/C/insert&selectionStruct.c
  Programing Language/C family/C/shelSort.c
  Programing Language/Java/Bank.java
  Programing Language/Java/Exception/Percobaan1/percobaan11.java
  Programing Language/Java/Exception/Percobaan1/percobaan12.java
  Programing Language/Java/Exception/Percobaan2/percobaan21.java
  Programing Language/Java/Exception/Percobaan2/percobaan22.java
  Programing Language/Java/Exception/Percobaan3/percobaan3.java
  Programing Language/Java/Exception/Percobaan4/ExcepTest.java
  Programing Language/Java/Exception/Percobaan5/ThrowDemo.java
  Programing Language/Java/Exception/Percobaan6/percobaan6.java
  Programing Language/Java/Exception/Tugas1/ReadFileThrow.java
  Programing Language/Java/Exception/Tugas1/Readfile.java
  Programing Language/Java/Exception/latihansoal1/checked.java
  Programing Language/Java/Exception/latihansoal1/unchecked.java
  Programing Language/Java/Exception/latihansoal2/ASE.java
  Programing Language/Java/Exception/latihansoal2/CCE.java
  Programing Language/Java/Exception/latihansoal2/NASE.java
  Programing Language/Java/Exception/latihansoal2/NFE.java
  Programing Language/Java/Exception/latihansoal2/NPE.java
  Programing Language/Java/Exception/latihansoal2/NSEE.java
  Programing Language/Java/Exception/latihansoal2/SIOOBE.java
  Programing Language/Java/Kerucut.java
  Programing Language/Java/Lingkaran.java
  Programing Language/Java/Nasabah.java
  Programing Language/Java/Silinder.java
  Programing Language/Java/buble sort.java
  Programing Language/Java/multiTabungan.java
  Programing Language/Java/tes.java
  Programing Language/Java/tesTugas.java
  Programing Language/python/buble sorting.py
  Programing Language/python/guestCode.py
  old project/Dev C/c++/Simpel calc/Makefile.win
  old project/Dev C/c++/Simpel calc/Project1.dev
  old project/Dev C/c++/Simpel calc/Project1.exe
  old project/Dev C/c++/Simpel calc/Project1.layout
  old project/Dev C/c++/Simpel calc/Project2.dev
  old project/Dev C/c++/Simpel calc/Project2.exe
  old project/Dev C/c++/Simpel calc/Project2.layout
  old project/Dev C/c++/Simpel calc/kalkulator simpel
  old project/Dev C/c++/Simpel calc/kalkulator simpel.cpp
  old project/Dev C/c++/Simpel calc/kalkulator simpel.exe
  old project/Dev C/c++/Simpel calc/kalkulator simpel.layout
  old project/Dev C/c++/Simpel calc/main.cpp
  old project/Dev C/c++/Simpel calc/main.o
  old project/Dev C/c++/Simpel calc/main2.cpp
  old project/Dev C/c++/Simpel calc/main2.o
Labels: documentation, enhancement, good first issue, hacktoberfest-accepted

#31 add net beans project mavenp0
  old project/Net Beans/mavenproject0/pom.xml
Labels: enhancement, hacktoberfest-accepted

#33 add oop java netbean
  old project/Net Beans/oop0/build.xml
  old project/Net Beans/oop0/build/built-jar.properties
  old project/Net Beans/oop0/build/classes/.netbeans_automatic_build
  old project/Net Beans/oop0/build/classes/.netbeans_update_resources
  old project/Net Beans/oop0/build/classes/oop0/Circle.class
  old project/Net Beans/oop0/build/classes/oop0/Ellipse.class
  old project/Net Beans/oop0/build/classes/oop0/Info.class
  old project/Net Beans/oop0/build/classes/oop0/Oop0.class
  old project/Net Beans/oop0/build/classes/oop0/Rectangle.class
  old project/Net Beans/oop0/build/classes/oop0/Square.class
  old project/Net Beans/oop0/dist/README.TXT
  old project/Net Beans/oop0/dist/oop0.jar
  old project/Net Beans/oop0/manifest.mf
  old project/Net Beans/oop0/nbproject/build-impl.xml
  old project/Net Beans/oop0/nbproject/genfiles.properties
  old project/Net Beans/oop0/nbproject/private/private.properties
  old project/Net Beans/oop0/nbproject/private/private.xml
  old project/Net Beans/oop0/nbproject/project.properties
  old project/Net Beans/oop0/nbproject/project.xml
  old project/Net Beans/oop0/src/oop0/Circle.java
  old project/Net Beans/oop0/src/oop0/Ellipse.java
  old project/Net Beans/oop0/src/oop0/Info.java
  old project/Net Beans/oop0/src/oop0/Oop0.java
  old project/Net Beans/oop0/src/oop0/Rectangle.java
  old project/Net Beans/oop0/src/oop0/Square.java
Labels: enhancement, hacktoberfest-accepted

#34 Move some files to their respective folders
  DOCUMENTATION.md
  Programing Language/PHP/halo.php
  Programing Language/donut template
Labels: enhancement, hacktoberfest-accepted

#36 add email checker in bash
  Programing Language/Bash/emailCheck.sh
Labels: enhancement, good first issue, hacktoberfest-accepted

#37 Add new contributors, add Rust folder, and rename Python folder
  CONTRIBUTING.md
  Programing Language/Python/buble sorting.py
  Programing Language/Python/guestCode.py
  Programing Language/Rust/testcase_list.rs
Labels: enhancement, hacktoberfest-accepted

#38 Add answer file for "formatting" in Rust by Example
  Programing Language/Rust/formatting.rs
Labels: documentation, enhancement, hacktoberfest-accepted
