Repository SilvaneUX/donut-test, pull requests merged in 2024-10, with the labels that each got.

#55 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#56 Added code for finding next greater element in C++
  Programing Language/C family/C++/next_greater_element.cpp
Labels: documentation, enhancement, hacktoberfest-accepted

#57 Updated CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#58 Added N-Queens solution using cpp.
  Programing Language/C family/C++/Nqueens.cpp
Labels: enhancement, hacktoberfest-accepted

#60 Added my fuzzing tool project in Go
  Programing Language/Go/FuzzerBuzzer/README.md
  Programing Language/Go/FuzzerBuzzer/app/app.go
  Programing Language/Go/FuzzerBuzzer/cmd/fuzzer.go
  Programing Language/Go/FuzzerBuzzer/config/config.yaml
  Programing Language/Go/FuzzerBuzzer/go.mod
  Programing Language/Go/FuzzerBuzzer/go.sum
  Programing Language/Go/FuzzerBuzzer/internal/fuzz_logic/fuzz.go
  Programing Language/Go/FuzzerBuzzer/internal/generator/input_gen.go
  Programing Language/Go/FuzzerBuzzer/internal/http/client.go
  Programing Language/Go/FuzzerBuzzer/internal/http/errors.go
  Programing Language/Go/FuzzerBuzzer/pkg/helpers.go
  Programing Language/Go/FuzzerBuzzer/tests/fuzzer_test.go
Labels: enhancement, hacktoberfest-accepted

#61 merge
  Programing Language/Java/ThreadExample.java
Labels: enhancement, hacktoberfest-accepted

#62 Create prime.py
  prime.py
Labels: documentation, enhancement, hacktoberfest-accepted

#63 merge sort added
  Programing Language/C family/C++/merge_sort.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#70 Create Maximum_Subarray_Sum.cpp
  Programing Language/C family/C++/Maximum_Subarray_Sum.cpp
Labels: documentation, enhancement, hacktoberfest-accepted

#71 Added Linear Search Algorithm in Python
  Programing Language/Python/linearsearch.py
Labels: enhancement, hacktoberfest-accepted

#73 Create huffmancoding.java
  Programing Language/Java/huffmancoding.java
Labels: enhancement, hacktoberfest-accepted

#75 Create Dfs&Bfs.py
  Programing Language/Python/Dfs&Bfs.py
Labels: enhancement, hacktoberfest-accepted

#76 solved Valid Sudoku in CPP
  Programing Language/C family/C++/Valid_sudoku.cpp
Labels: enhancement, hacktoberfest-accepted

#77 Create FrogJump.cpp
  Programing Language/C family/C++/FrogJump.cpp
Labels: enhancement, hacktoberfest-accepted

#79 commited for added Armstrong no program
  Programing Language/PHP/Armstrong_no.php
Labels: enhancement, hacktoberfest-accepted

#80 Added Factorial Program in C #78
  Programing Language/C family/C/a.exe
  Programing Language/C family/C/factorial.c
Labels: enhancement, hacktoberfest-accepted

#81 Create Sliding Window Maximum.cpp
  Programing Language/C family/C++/Sliding Window Maximum.cpp
Labels: enhancement, hacktoberfest-accepted

#82 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#83 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement, hacktoberfest-accepted

#85 palindrome number
  palindrome number
Labels: enhancement, hacktoberfest-accepted

#86 armstrong number
  armstrong number
Labels: enhancement, hacktoberfest-accepted

#87 find factorial
  factorial
Labels: enhancement, hacktoberfest-accepted

#88 heart disesases project added
  old project/heart disease prediction/heart_disease_classification.ipynb
  old project/heart disease prediction/jupyuter_markdown.ipynb
Labels: enhancement, hacktoberfest-accepted

#90 Create ReverseStackUsingRecursion.java
  ReverseStackUsingRecursion.java
Labels: enhancement, hacktoberfest-accepted

#92 Second Largest Element in an Array without sorting.
  Programing Language/Java/findSecondLargest.java
Labels: enhancement, hacktoberfest-accepted

#93 Update README.md
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted

#94 Added Error Handling in Rust
  Programing Language/Rust/Error Handling/README.md
  Programing Language/Rust/Error Handling/abort and unwind.rs
  Programing Language/Rust/Error Handling/panic.rs
Labels: documentation, enhancement, hacktoberfest-accepted

#95 Reverse an Array
  CONTRIBUTING.md
  Reversing an array
Labels: enhancement, hacktoberfest-accepted

#97 Create dynamic_fibonacci.py
  dynamic_fibonacci.py
Labels: enhancement, hacktoberfest-accepted

#98 Create diamon_pattern.py
  diamon_pattern.py
Labels: enhancement, hacktoberfest-accepted

#100 Added names in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, enhancement, hacktoberfest-accepted

#101 Create factoryPatter.java
  CONTRIBUTING.md
  Programing Language/Java/factoryPatter.java
Labels: enhancement, hacktoberfest-accepted
