Repository SilvaneUX/donut-test, pull requests merged in 2025-10, with the labels that each got.

#105 add bounding box app
  Programing Language/Python/aplikasi_bounding_box.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#109 Sorting it again
  Programing Language/Python/windows water reminder/main.py
  Programing Language/Python/windows water reminder/water.png
Labels: documentation, enhancement, hacktoberfest-accepted

#115 Added Merge Sort in Java
  Programing Language/Java/MergeSort.java
Labels: enhancement, hacktoberfest-accepted

#116 Added Insertion Sort implementation in Java
  CONTRIBUTING.md
  Programing Language/Java/InsertionSort.java
Labels: documentation, enhancement, hacktoberfest-accepted

#119 I have added binary search code in java
  Programing Language/Flutter/dcd_newsapp_fundamental - buntu v0.000 (gagal fetch api)/android/gradle/wrapper/gradle-wrapper.properties
  Programing Language/Java/BinarySearch.class
  Programing Language/Java/BinarySearch.java
Labels: enhancement, hacktoberfest-accepted

#127 dfs.c
  Programing Language/C family/C/dhs.c
Labels: enhancement, hacktoberfest-accepted
